### ISSUE TITLE
Error while running pep.py

### ISSUE THREAD

**Issue by FischiTheDev** [Uniminin/Light-Ripple-Windows#25]
E:\Light-Ripple-Windows\pep.py>python pep.py
Traceback (most recent call last):
  File "E:\Light-Ripple-Windows\pep.py\pep.py", line 12, in <module>
    from common import generalUtils, agpl
  File "E:\Light-Ripple-Windows\pep.py\common\generalUtils.py", line 5, in <module>
    from common.log import logUtils as log
  File "E:\Light-Ripple-Windows\pep.py\common\log\logUtils.py", line 3, in <module>
    from objects import glob
  File "E:\Light-Ripple-Windows\pep.py\objects\glob.py", line 6, in <module>
    from objects import channelList
  File "E:\Light-Ripple-Windows\pep.py\objects\channelList.py", line 4, in <module>
    from helpers import chatHelper as chat
  File "E:\Light-Ripple-Windows\pep.py\helpers\chatHelper.py", line 5, in <module>
    from constants import serverPackets
  File "E:\Light-Ripple-Windows\pep.py\constants\serverPackets.py", line 7, in <module>
    from helpers import packetHelper
ImportError: cannot import name 'packetHelper' from 'helpers' (E:\Light-Ripple-Windows\pep.py\helpers\__init__.py)

**Comment by FischiTheDev** [comment]
And this one:
Traceback (most recent call last):
  File "E:\Light-Ripple-Windows\lets\lets.py", line 10, in <module>
    from raven.contrib.tornado import AsyncSentryClient
  File "C:\Users\nicon\AppData\Roaming\Python\Python39\site-packages\raven\__init__.py", line 54, in <module>
    from raven.base import *  # NOQA
  File "C:\Users\nicon\AppData\Roaming\Python\Python39\site-packages\raven\base.py", line 688
    if transport.async:
                 ^
SyntaxError: invalid syntax
